openapi: 3.1.1
info:
  title: soto-account
  description: soto-account の API仕様書
  version: "1.0"
servers:
  - url: https://soto-account.deno.dev/
paths:
  /accounts:
    get:
      summary: List all accounts
      operationId: listAccounts
      tags:
        - Accounts
      responses:
        '200':
          description: A list of accounts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
    post:
      summary: Create a new account
      operationId: createAccount
      tags:
        - Accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAccount'
      responses:
        '201':
          description: Account created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
  /accounts/{account_id}:
    get:
      summary: Get a account by ID
      operationId: getAccountById
      tags:
        - Accounts
      parameters:
        - name: account_id
          in: path
          required: true
          schema:
            type: integer
        - name: includePosts
          in: query
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: A account object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
components:
  schemas:
    Account:
      type: object
      properties:
        account_id:
          type: integer
          format: int
        account_name:
          type: string
        balanse:
          type: integer
    NewAccount:
      type: object
      required:
        - account_name
      properties:
        account_name:
          type: string