openapi: 3.1.1
info:
  title: Soto Purchase API
  description: API specification for the Soto Purchase service
  version: 1.0.0
servers:
  - url: https://soto-purchase.deno.dev/
    description: Production Server
  - url: http://localhost:8001/
    description: Local Development Server
paths:
  /purchase:
    post:
      summary: Purchase a Kuji
      operationId: purchaseKuji
      tags:
        - Purchase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseRequest'
      responses:
        '201':
          description: purchase done.
  /events:
    get:
      summary: List all events
      operationId: listEvents
      tags:
        - Events
      responses:
        '200':
          description: A list of events.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
components:
  schemas:
    PurchaseRequest:
      type: object
      required:
        - eventId
        - accountId
        - selectedNumber
      properties:
        eventId:
          type: integer
          format: int64
          example: 1
        accountId:
          type: integer
          format: int64
          example: 1
        selectedNumber:
          type: integer
          format: int64
          example: 1
    Event:
      type: object
      properties:
        eventId:
          type: integer
          format: int
          example: 1
        optionCount:
          type: int
          example: 1
        winningNumber:
          type: integer
          example: 1
        prizeMoney:
          type: integer
          example: 5000
        isSelling:
          type: integer
          example: 1
        endSaleDate:
          type: integer
          example: "2025-01-31T14:59:59.000Z"
